{% set name = "bindsnet" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b4d445d5ad5d249720ad09423e9ecb97ea98cceec2ad4a2e7373b17185fde3b9

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
    - setuptools
  run:
    - cython
    - matplotlib-base
    - numpy
    - opencv
    - pandas
    - python >={{ python_min }},<3.12
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboardx
    - pytorch
    - torchvision
    - tqdm
    - foolbox
    - ale-py
    - gymnasium

test:
  requires:
    - python {{ python_min }}
  imports:
    - bindsnet

about:
  home: https://github.com/BindsNET/bindsnet
  summary: Spiking neural networks for ML in Python
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
