{% set name = "bindsnet" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9bae6a0bd9adeeaa6f889d610daef32f557758e01fbb65fdd1c8ea0a72e53e28

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python >=3.9,<3.12
    - poetry
    - setuptools
  run:
    - cython
    - matplotlib-base
    - numpy
    - opencv
    - pandas
    - python >=3.9,<3.12
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboardx
    - pytorch
    - torchvision
    - tqdm
    - foolbox
    - ale-py
    - gymnasium

test:
  imports:
    - bindsnet

about:
  home: https://github.com/BindsNET/bindsnet
  summary: Spiking neural networks for ML in Python
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
